# https://github.com/wurstmeister/kafka-docker
# https://stackoverflow.com/a/68747907/11868833
# https://thepracticaldeveloper.com/spring-boot-kafka-config/

version: '3'
services:
  zookeeper-server:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka-server:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-server:2181
