# gateway-server-development at default port 8080
#server:
#  port: ${app_port}
spring:
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      routes:
      - id: shop-route
        uri: lb://shop-service
        predicates:
        - Path=/shop/**
# RewriteLocationResponseHeader 3rd parameter must be the same as the Gateway path
        filters:
        - RewritePath=/shop(?<segment>.*), /shop$\{segment}
        - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, localhost:8080/shop
        - LevelledRequestLogger=INFO
    discovery:
      locator:
        enabled: true
eureka:
  client:
    should-enforce-registration-at-init: true
    serviceUrl:
      defaultZone:
        http://localhost:${DISCOVERY_SERVER_PORT}1/eureka/
#        http://localhost:${DISCOVERY_SERVER_PORT}2/eureka/  # ha mode
    registry-fetch-interval-seconds: 1${DISCOVERY_REGISTRY_INTERVAL}
  instance:
    prefer-ip-address: true
    metadataMap:
      zone: ${zone_name}
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
# loggers config
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE