# payment-service-development
server:
  port: ${app_port}
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        payments-shop-out-0: # must be the same in EventEmitter
          destination: payment-shop-events
        payments-order-out-0: # must be the same in EventEmitter
          destination: payment-order-events
eureka:
  client:
    should-enforce-registration-at-init: true
    serviceUrl:
      defaultZone:
        http://localhost:${DISCOVERY_SERVER_PORT}1/eureka/
#        http://localhost:${DISCOVERY_SERVER_PORT}2/eureka/  # ha mode
    registry-fetch-interval-seconds: 1${DISCOVERY_REGISTRY_INTERVAL}
  instance:
    prefer-ip-address: true
    metadataMap:
      zone: ${zone_name}
