# shop-service-high-availability
server:
  port: ${app_port}
spring:
  jackson:
    default-property-inclusion: always
  cloud:
    function:
      definition: paymentShopEventsConsumer
    stream:
      bindings:
        paymentShopEventsConsumer-in-0:
          destination: payment-shop-events
          group: shop-001
eureka:
  client:
    should-enforce-registration-at-init: true
    serviceUrl:
      defaultZone:
        http://localhost:${DISCOVERY_SERVER_PORT}1/eureka/,
        http://localhost:${DISCOVERY_SERVER_PORT}2/eureka/
    registry-fetch-interval-seconds: ${DISCOVERY_REGISTRY_INTERVAL}
  instance:
    prefer-ip-address: true
    metadataMap:
      zone: ${zone_name}
feign:
  circuitbreaker:
    enabled: true